### ISSUE TITLE
Hope to get full model code

### ISSUE THREAD

**Issue by SCAUapc** [EMNLP2019LSAN/LSAN#1]
Hi !  I  like your work, can you push the full model code? I check the model code and find that it  incompletable.

**Comment by SCAUapc** [comment]
I have complete the code by myself, thanks

**Comment by benbijituo** [comment]
Do you know how to get the label embeddings? They are not randomly initialized.

**Comment by SCAUapc** [comment]
@benbijituo  
Sorry, i forget to response you.
I have wrired  the  whole  model and use the glove the init the label embedding, this method is common, i suggest you do  that too. 
I use my complement code and author 's data, and add some dropout. I get  better performance than the paper...
If  you  need the complement code , call me. But I can not  commit the code util tonight.  
Maybe we can discuss together.

**Comment by benbijituo** [comment]
> @benbijituo
> Sorry, i forget to response you.
> I have wrired the whole model and use the glove the init the label embedding, this method is common, i suggest you do that too.
> I use my complement code and author 's data, and add some dropout. I get better performance than the paper...
> If you need the complement code , call me. But I can not commit the code util tonight.
> Maybe we can discuss together.

Thank you so much for your answer in time.
I desire to read your complete code. Could you please send it to benbijituo@gmail.com?
Appreciate it!

**Comment by JaeZheng** [comment]
> @benbijituo
> Sorry, i forget to response you.
> I have wrired the whole model and use the glove the init the label embedding, this method is common, i suggest you do that too.
> I use my complement code and author 's data, and add some dropout. I get better performance than the paper...
> If you need the complement code , call me. But I can not commit the code util tonight.
> Maybe we can discuss together.

@SCAUapc 
It's so nice for you to contribute to this open source work！
I desire to read your complete code. Could you please send it to jaezheng@foxmail.com?
Appreciate it!

**Comment by zzzmm1** [comment]
@SCAUapc
Thanks for your contribution！
Could you please send it to ajyjzju@foxmail.com?
Appreciate it!

**Comment by yy-mille** [comment]
> @benbijituo
> Sorry, i forget to response you.
> I have wrired the whole model and use the glove the init the label embedding, this method is common, i suggest you do that too.
> I use my complement code and author 's data, and add some dropout. I get better performance than the paper...
> If you need the complement code , call me. But I can not commit the code util tonight.
> Maybe we can discuss together.



> I have complete the code by myself, thanks

Thanks for your contribution！
Could you please send it to 2778142138@qq.com?
Appreciate it!

**Comment by shuxiaobo** [comment]
Hi, Is there anyone get the better code? Coule you please sent me a copy? Thanks very much. @SCAUapc @benbijituo @xiyang-lili @zzzmm1 
helloshane@qq.com

**Comment by yuccccci** [comment]
You are so great, could you send me your full code for reference. I need it and would appreciate it! My email address is yuccccci1130@163.com @SCAUapc

**Comment by SCAUapc** [comment]
> You are so great, could you send me your full code for reference. I need it and would appreciate it! My email address is [yuccccci1130@163.com](mailto:yuccccci1130@163.com) @SCAUapc

Hi, I find that this repo is now complete, I think you can use the code itself ? My code is nearly 3 years ago..and now I can not find it... sry
